### ISSUE TITLE
Breaking the concept of "pending block"

### ISSUE THREAD

**Issue by aneequesafdar** [clearmatics/autonity#109]
[stevenroose](https://github.com/stevenroose) pointed out in [EIP 650](https://github.com/ethereum/EIPs/issues/650#issuecomment-360085474) that the concept of "pending block" is broken by the current implementation of Istanbul. This is something we need to keep in mind and investigate for Istanbul and Tendermint implementation.

**Comment by JekaMas** [comment]
Is it still an issue? https://github.com/ethereum/go-ethereum/pull/15963#issuecomment-453038411
