### ISSUE TITLE
Estimate effort to comply with the EEA Permissioning Specification

### ISSUE THREAD

**Issue by shapeshed** [clearmatics/autonity#119]
The [Ethereum Enterprise Alliance Specification][1] version 3 was published recently and standardises the permissioning approach for EEA clients. The approach is similar to the approach that Autonity takes.

The ask for this issue is to _estimate_ the effort required to implement the interface expressed in 7.3.3 of the specification. No development work is needed. In the permissioning model the interface is separated from the implementation of the permissioning model. 

This can be scheduled for the next sprint, discussed on the issue and is not urgent. 

Related issues:
* [Network Permissioning #72][2]
* [Tests for current implementation of Network Permissioning #91][3]

[1]: https://entethalliance.org/wp-content/uploads/2019/05/EEA_Enterprise_Ethereum_Client_Specification_V3.pdf 
[2]: https://github.com/clearmatics/autonity/issues/72
[3]: https://github.com/clearmatics/autonity/issues/91

**Comment by JekaMas** [comment]
Really interesting! Going to start reading the specification this week.

**Comment by shapeshed** [comment]
Any update on this one please?
