### ISSUE TITLE
Refactor `latestPendingUnminedBlock` in tendermint/core.go

### ISSUE THREAD

**Issue by aneequesafdar** [clearmatics/autonity#136]
`latestPendingUnminedBlock` keeps track of the potential future proposal, we want `latestPendingUnminedBlock` to be the current height and most updated at the time of proposal so that we have latest transactions in the block. There is an event `NewUnmineBlockEvent` which signals to the consensus layer that a new "unmined" block is available and this event's handler updates the `core.latestPendingUnminedBlock`.

If the `c.latestPendingUnminedBlock == nil` at startup or `latestPendingUnminedBlock` height is not the same then start round will wait for a `NewUnminedBlockEvent`.

The current implementation uses a channel and boolean values to coordinate, however, it is not ideal. So we need to refactor how `c.latestPendingUnminedBlock` is updated.

**Comment by JekaMas** [comment]
closed in favour https://github.com/clearmatics/autonity/issues/142
