### ISSUE TITLE
Glieniecke contract and enodes resolving issue

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#154]
There is an issue when running Autonity on a private network.

I can't manage to run my run my local network : the nodes can't connect between themselves (peer is not authorized error)

My genesis config:

```
{
    "config": {
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantinumBlock": 0,
        "istanbul": {
            "policy": 0,
            "epoch": 30000,
            "contract-deployer": "0x0000000000000000000000000000000000000001",
            "bytecode": "",
            "abi": ""
        },
        "chainId": 1991,
        "enodeWhitelist": [
            "enode://c3913c0c93e7ae8722e72df3c3abff343dabb62855543902b9687c8ceeb4c7a5cafeeb30aeecb41acb0ababec2e5da498386fce576366b01eabb5b7153d580ca@127.0.0.1:5000",                                                                                                                   
            "enode://bd6e79c8cf48ce627f0512fcb7339e906554bfb189c2691b3abf32ea69318937ceec3098f1858c5624bc813d8b543ebb3b80dadef0c1bac9dccf3eda55009c0b@127.0.0.1:5001",                                                                                                                   
            "enode://5b527e5683ae8513cc4aacb61af19aee0a3570a91cb7fecc6b262b0d3de2ca7c7ba8ad4173ad1669c14241531533ea3241f965de481a692b9aa895fffc4e394f@127.0.0.1:5002",                                                                                                                   
            "enode://3b6169937ea8ea2b5d8f072d904572144e39b6784e2d48e6e8d2fef13f2664b89c5862992b180ee02e0e5c39a1c8d684e3017274084120f88c5d498e9ab9cbb1@127.0.0.1:5003"                                                                                                                    
        ],
        "glienickeDeployer": "0x0000000000000000000000000000000000000002",
        "glienickeBytecode": "",
        "glienickeABI": ""
    },
    "nonce": "0x0",
    "timestamp": "0x0",
    "gasLimit": "0x5F5E100",
    "difficulty": "0x1",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "number": "0x0",
    "gasUsed": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "alloc": {
        "0x2d90a507d1cafbbbf05e517fcdf896ba17917cd2": {
            "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
        },
        "0x1135b2d2682e377b56f449a8bd4071686ccf52ba": {
            "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
        },
        "0x4113fe1a8560c1ad9105c7654279aeea1e03b215": {
            "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
        },
        "0x8b145265477cc0c51ac2d5bbf9c5cbe7c0880fc4": {
            "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
        }
    },
    "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f89af854942d90a507d1cafbbbf05e517fcdf896ba17917cd2941135b2d2682e377b56f449a8bd4071686ccf52ba944113fe1a8560c1ad9105c7654279aeea1e03b215948b145265477cc0c51ac2d5bbf9c5cbe7c0880fc4b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0"
}

```

Flags :
```
/autonity --datadir ./network-data/node0/data/ --nodekey ./network-data/node0/boot.key --syncmode 'full' --port 5000 --rpcport 6000 --rpc --rpcaddr '0.0.0.0' --rpccorsdomain '*' --rpcapi 'personal,db,eth,net,web3,txpool,miner,istanbul,clique' --networkid 1991  --gasprice '0'  --unlock 0x2d90a507d1cafbbbf05e517fcdf896ba17917cd2 --password ./network-data/node0/pass.txt --debug --mine --verbosity 4
```

I think the root of the issue is coming from the function `filterNodes()` in `core/types/nodes.go`
with `filtered.StrList = append(filtered.StrList, n.StrList[i])` happening only if openNetwork is true.

Besides that, I can't see anywhere the returned list being sorted, which is important because we need deterministic constructor arguments being passed to the Glienicke contract. 

Finally, the code in `core/types/nodes.go` is very badly documented and variable name can be better chosen. I think there is a lot of room for improvement for this type, I've missed it during the code review, will create a new issue for this one.

**Comment by aneequesafdar** [comment]
I am not sure why you are having problems but HelloWorld docker file on the master branch is working fine. And OpenNetwork flag by default is false, so I don't think that is the issue. Also, you haven't described what the issue you have encountered.

I am not sure what you expect for documentation, do you want a separate document for every change that is made? If so, then who will be responsible for managing those documents, where will they be stored and to what detail do they need to be?

Usually, the pull request describes the issue and the commits are also describing the changes. Sure it is lacking comments but its not the best use of developers time to do the changes in code and then describe them in exact detail again in another document, it makes the pull request and commits messages redundant.

**Comment by yazzaoui** [comment]
> I am not sure why you are having problems but HelloWorld docker file on the master branch is working fine. 

Even if the docker HelloWorld is working fine it doesn't mean the system is bug-free, maybe the docker has a specific genesis configuration that works but under my own configuration (which was previously working well) it doesn't work anymore. 

>  Also, you haven't described what the issue you have encountered.

Yeah, it's not clear described, peers are denied to connect ( permissionning issue) 

> 
> I am not sure what you expect for documentation, do you want a separate document for every change that is made? If so, then who will be responsible for managing those documents, where will they be stored and to what detail do they need to be?
> 

For this one, I'm not expecting a full-fledged separate document (although I wouldn't say no if you did), but rather documentation in the form of code comments.


> Usually, the pull request describes the issue and the commits are also describing the changes. Sure it is lacking comments but its not the best use of developers time to do the changes in code and then describe them in exact detail again in another document, it makes the pull request and commits messages redundant.

This is not good software engineering practice, as a developer I don't want to look for the specific pull-request (platform dependent) to understand what's going on. Also, commits can be lost due to rebasing.

It's important to learn how to comment your code properly, it would help your fellow developer to understand what was the original intention of the logic and help yourself 6 months later when you will have forgotten what your own code was supposed to do ( trust me it happens all the time).

**Comment by aneequesafdar** [comment]
> Even if the docker HelloWorld is working fine it doesn't mean the system is bug-free, maybe the docker has a specific genesis configuration that works but under my own configuration (which was previously working well) it doesn't work anymore.

You still haven't said what the issue is, logs and a way to reproduce them will help.

Documentation and comments are completely two different things, also you approved the pull request (and at that time comments and documentation were enough but not now). There are virtually no comments on the initial network permission code either nor is there any tests, which is again a shortcoming of only doing code review.

**Comment by JekaMas** [comment]
We are developers. If we see something to improve we always can write some code and show our idea.

**Comment by yazzaoui** [comment]
Ok guys we can discuss outside from gitthub those points but was anyone able to reproduce the issue? I'm using [this](https://github.com/clearmatics/local-autonity-deployment-utility/blob/master/main.py) deployment script, what more information do you need? 

Have you tried to start a private network without using the docker image?

**Comment by JekaMas** [comment]
@yazzaoui As you can see `helloworld` example is set up as a private network of 5 nodes - `helloworld/genesis-ibft.json`. I think it could be better to run it and check any hypothesis you need.

**Comment by aneequesafdar** [comment]
@yazzaoui the autonity binary is always compiled from scratch in the docker image, also there are scripts and a Readme in the `helloworld`, please read those to diagnose your issue.

**Comment by aneequesafdar** [comment]
Also, I am pretty sure the biggest reason for it not working is that for devops there was a requirement to not create `extradata` externally rather inside the client so genesis file was extended to take validators as a list and then create extradata, but your script doesn't handle that.

Again these are guesses, you still haven't shared any error messages or log messages.

**Comment by b00ris** [comment]
I can't reproduce the problem.
The `helloworld` example works well.
I've assembled local cluster using the issue genesis and keys from autonity/helloworld but it works well too.
```55:12.013|core/state/statedb.go:665]                 Trie cache stats after commit            misses=0 unloads=0
DEBUG[07-02|19:55:12.013|core/blockchain.go:1238]                   Inserted new block                       number=32 hash=cb3c7d…08616a uncles=0 txs=0 gas=0 elapsed=1.340ms   root=0faff1…b41eab
INFO [07-02|19:55:12.013|core/blockchain_insert.go:74]              Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=2.318ms   mgasps=0.000 number=32 hash=cb3c7d…08616a cache=14.59kB
DEBUG[07-02|19:55:12.013|core/tx_pool.go:418]                       Reinjecting stale transactions           count=0
INFO [07-02|19:55:12.013|miner/worker.go:990]                       Commit new mining work                   number=33 sealhash=38fd84…63e70b uncles=0 txs=0 gas=0 fees=0 elapsed=373.728µs
```
I think we should close the issue as 'can't reprocuce'.

**Comment by yazzaoui** [comment]
Going to close this issue until we get more information on the scope of supported configurations.
