### ISSUE TITLE
Glienicke contract - non deterministic constructor arguments

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#165]
Not entirely sure about this one but when deploying the Glienicke contract 
(`core/network_permissioning.go`) , we need a deterministic list of enodes for the smart-contract constructor parameters, if not we will have some serious consensus issues.

It seems like the `NewNodes()` function in `core/types/nodes.go` is possibly not returning this list of addresses in a deterministic way.

The task is :
- To confirm that there is indeed a potential problem.
- And if so, propose a solution.

**Comment by b00ris** [comment]
I've not found a problem. There is a sorting function for enodes before Glienicke contract deployment.(https://github.com/clearmatics/autonity/blob/dc08ab372cb0514b3284f23e52b6d4487ad39b0c/core/network_permissioning.go#L117)
