### ISSUE TITLE
Consensus should continue if 1/3N nodes go down and start again

### ISSUE THREAD

**Issue by aneequesafdar** [clearmatics/autonity#177]
Based on the tendermint specification there is no mention of re-sending already broadcasted messages, this is problematic if 1/3N honests node goes down without anyone's fault and come back up then the consensus should continue. However, in the current implementation where there is no re-sending of old messages, the consensus will be halted even if all of the validators are online.

One solution is for validators to send their consensus state after block synchronisation has finished, to allow for consensus to continue.

**Comment by JekaMas** [comment]
As it's implemented in tendermine by cosmos it should be responsibility of the node to ask it's peers about the current height+round. So we can introduce a new message 'getConsensusState'.
The second thing is about round changing. I think we should increase round if a proposer didn't manage to send to the node a correct block.

This two things shout give liveness.

**Comment by aneequesafdar** [comment]
> I think we should increase round if a proposer didn't manage to send to the node a correct block.

I am not sure what you mean by above, how would the proposer know the node didn't get a correct block?

**Comment by JekaMas** [comment]
No-no, I think that all other nodes should have timeout waiting for the current proposer.

**Comment by aneequesafdar** [comment]
They do in tenermint/core/core.go:

```go
if c.isProposer() {
		if c.validValue != nil {
			p = c.validValue
		} else {
			c.latestPendingUnminedBlockMu.RLock()
			p = c.latestPendingUnminedBlock
			c.latestPendingUnminedBlockMu.RUnlock()
		}
		c.sendProposal(p)
	} else {
		timeoutDuration := timeoutPropose(round.Int64())
		c.proposeTimeout.scheduleTimeout(timeoutDuration, round.Int64(), height.Int64(), c.onTimeoutPropose)
		c.logger.Debug("Scheduled Propose Timeout", "Timeout Duration", timeoutDuration)
	}
```

If you are not the proposer you start the timeout.

**Comment by yazzaoui** [comment]
depreciated, closing
