### ISSUE TITLE
Change Round and Height number in tendermint to int and use atomic value to manage synchronicity

### ISSUE THREAD

**Issue by aneequesafdar** [clearmatics/autonity#178]
In tendermint, round number and height type are `*big.Int` this is not required and is only used for rlp encoding, so when encoding and decoding just change types in between. This makes it easier to manage height and round numbers and reduces overhead on synchronicity.

**Comment by JekaMas** [comment]
@aneequesafdar do we need this?

**Comment by aneequesafdar** [comment]
Its not required, its just refactoring. I just opened it so that we don't forget a possible refactor.
