### ISSUE TITLE
Investigate backlog sendEvent

### ISSUE THREAD

**Issue by aneequesafdar** [clearmatics/autonity#179]
`tendermint.MessageEvent` and `backlogEvent`  share the same subscription, so we had to send backlogEvent as a separate go routine, we weren#t sure why this was the case and when we tried to use on subscription per message that still didn't work, some code is on a branch called Some existing code on a branch `separate-type-sub-for-backlog`.

**Comment by JekaMas** [comment]
@aneequesafdar how do you think could we close the issue?

**Comment by aneequesafdar** [comment]
We find an explanation of how TypeMuxSubcription work and have a subscription of each event separately
