### ISSUE TITLE
Upgradability, from 0.1.0 to 1.0.0

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#184]
Hi all,

As you may be aware, or may not, the 1.5 release needs to incorporate some basic elements for network economics until the final version that should be delivered early next year. If you don't have access to the SRS requirements please let me know on slack.

My main concern is how are we going to perform the "on-the-fly"  upgrade, as it is apparently unacceptable to restart from Genesis the 1.5 release deployed network. Therefore a hard fork seems to be the apparently the way to go, but if done the wrong way this would incur huge technical debts: we would have to keep and maintain legacy depreciated 1.5 code in the client..

**The consensus team proposal is to limit changes to be applied for this hard fork to an upgrade of the Autonity Contract exclusively**  as the bulk of network economics logic is being embedded into it. 

We've identified 4 points for core development to be done for the 1.5 release, even though they would not provide any new functionalities :

1. The consensus proposer retrieval function needs to call the Autonity Contract with the current native code being translated to solidity. 

2. Consensus messages need to be weighted by voting power, retrieved from the Autonity contract and being all equal weight for the v1.5.

3. Soma and Glieniecke contract need to be merged into the Autonity Contract and more suitable genesis file configuration format needs to be designed.

4. Omission faults accountability requires for the current proposer to include received pre-commits for the last mined block, this needs either to be included into a new header field OR extending extra-data.

Those are the main points we've currently identified, and maybe there is more to come, I'm encouraging everyone to think about this and to provide feedback, thanks!

**Comment by JekaMas** [comment]
It seems that https://github.com/clearmatics/autonity/pull/121
is still relevant

**Comment by aesmonty** [comment]
@JekaMas yes, parts of it. In particular, we are introducing the concept of voting power (even if is set to 1 by default) in Autonity. However, we are not planning to implement the weighted round-robin proposer freq of that PR.

**Comment by JekaMas** [comment]
It's not clear `Consensus messages need to be weighted by voting power...`
Is it only about adding `Power` field that does nothing?

**Comment by aesmonty** [comment]
> Is it only about adding Power field that does nothing?
Exactly, but just for the Platform X MVP. In this way, it will be much cleaner to upgrade the logic for subsequent releases post-MVP.

**Comment by JekaMas** [comment]
ok.
`more suitable genesis file configuration format needs to be designed` - what it's about? what coals do we have?

**Comment by aesmonty** [comment]
Atm, we get a list of addresses (Soma) and enodes (Glienicke) from Genesis.
For the MVP, we would need something in the lines of:

`Partipants = [(address, enode, memberType, stake),...]`

with memberType being either `standard user` or `member`.

For more info, have a look at the different types of members in the SRS or the ASC1 Spec, and if you have any doubt I'm happy to jump in a quick call :)

**Comment by JekaMas** [comment]
Maybe it's better to have 2 lists? Having single list with different types will cause difficulties for search or applying some function to particular type.

**Comment by Shirikatsu** [comment]
There is an open question regarding key management of validator signing keys. MVP likely will use cloud HSM for key management and signing and end state is TBD. However we have yet to consider implementing a solution such as [KMS](https://github.com/tendermint/kms) to manage the keys that sign validator messages.

**Comment by JekaMas** [comment]
@yazzaoui @shapeshed @aneequesafdar Am I right, that we decided to not follow SemVer and set versions using some other ways?

**Comment by shapeshed** [comment]
My view is that we should follow SemVer since this is a standard across other teams. Happy to discuss.

**Comment by JekaMas** [comment]
@b00ris @yazzaoui  Am I right that https://github.com/clearmatics/autonity/pull/231 is a part of this issue?
Could we update the current issue and write a new one for https://github.com/clearmatics/autonity/pull/231 ?

**Comment by yazzaoui** [comment]
#231 is for https://github.com/clearmatics/autonity/issues/191
