### ISSUE TITLE
New genesis file format

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#186]
As per  #184 
it is proposed to introduce a new genesis file format with Soma and Glieniecke relevant fields being removed and a new `AutonityContract` field being created.

## Option 1

A clean format more suitable for 1.0.0. 

```json
"autonityContract": {
  "deployer": "0x0000000000000000000000000000000000000002",
  "bytecode": "xx",
  "abi": "xx",
  "minGasPrice":5000,
  "governanceOperator": "0x0000000000000000000000000000000000000003",
  "users": [
    {
      "address" : "0xa21ebc05046697bf882670905bce8306d53bdd18",
      "enode" : "enode://012112@domain.com",
      "type" : "participant",
      "stake" : 0,
    },
    {
      "enode" : "enode://012112@domain.com",
      "type" : "member",
      "stake" : 5,
    },
    {
      "enode" : "enode://012112@domain.com",
      "type" : "validator",
      "stake" : 5,
    }
  ],
},
```

An object *user* belonging to *autonityContract.users* contains 4 fields: **address**, **enode**, **type** and **stake**.

- *user.type* must be defined.

- *user.enode* or *user.address* must be defined.

- If both *user.enode* and *user.address* are defined, then the derived address from *user.enode* must be equal to *user.address*.

- If *user.enode* field is present then the full node assossiate must be allowed to access the network (network permissionning)

- *user.stake* must be nil or equal to 0 for users of type participant.

- If *user.type* is *validator* then *user.enode* must be defined.

## Option 2

Simple format with less constraints.

```json
"autonityContract": {
  "deployer": "0x0000000000000000000000000000000000000002",
  "bytecode": "xx",
  "abi": "xx",
  "minGasPrice":5000,
  "governanceOperator": "0x0000000000000000000000000000000000000003",
  "validators": [
    "0xa21ebc05046697bf882670905bce8306d53bdd18",
    "0xa21ebc05046697bf882670905bce8306d53bdd19",
    "0xa21ebc05046697bf882670905bce8306d53bdd20",
    "0xa21ebc05046697bf882670905bce8306d53bdd21"
  ],
  "stake-holders": [
    {
      "address" : "0xa21ebc05046697bf882670905bce8306d53bdd19",
      "stake" : 3,
    },
    {
      "address" : "0xa21ebc05046697bf882670905bce8306d53bdd19",
      "stake" : 10,
    }
  ],
  "authorized-enodes" : [
    "enode://123456@domain.com",
    "enode://986544@domain.com",
    "enode://12131@domain.com",
    "enode://126@domain.com",
    "enode://1256@domain.com",
  ]
},
```

- A validator's address must have its associated authorized-enode.

## User classes and constraints
- **participant**: Authorized to operate a full node, is able to join the network, is not authorized to own stake.
- **member**: Authorized to operate a full node, is able to join the network, authorized to own stake.
- **validator**:  Authorized to operate a full node, is able to join the network, authorized to own stake, participate in consensus.

## Questions to answer

1. Should `autonityContract` sit under `config` or be a root level field? The former is what I would do intuitively and would require to update `params.ChainConfig`. 
2. As per https://github.com/clearmatics/autonity/issues/184#issuecomment-509980491 , can we split the `autonityContract.user` field into multiple fields depending on `autonityContract.user.type` ?.
3. Do we still need to include the redundant `autonityContract.users.address` field that could be retrieved from the enode? [EDIT: The address field was removed]

### Changelog
-  [2019-07-26] Added Option 2, restored address field for option 1 and expressed constraints.
-  [2019-07-23] Removed address field, added user classes and constraints, added governanceOperator address.
-  [2019-07-22] Added minGasPrice field

**Comment by aneequesafdar** [comment]
Maybe a naive question: why not precompiles? I am sure precompiles can be upgraded or not

**Comment by b00ris** [comment]
@aneequesafdar Sure. Precompiled contracts can be upgradable too. But it has to update 2/3+1 of autonity node to make network workable. Also, It could be quite annoying for stakeholders. It’s a problem which faced applications based on cosmos SDK. If you want to update your application you have to recompile and restart validators(if you are not using ABCI over TCP(but it’s not recommended)).   If we want to update Solidity contract we need to accept the block with an update.

**Comment by b00ris** [comment]
1. I didn't get the idea why we need to update `params.ChainConfig`. I could be missing something.
2. I thought about it, but i decided to keep one list. 
3. We can do it. But i think it can introduce more complexity. I decided not to do it now.
```
func TestCheckKeys(t *testing.T)  {
	k,err:=crypto.GenerateKey()
	if err!=nil {
		t.Fatal(err)
	}
	pubkey:=k.PublicKey
	t.Log(enode.PubkeyToIDV4(&pubkey).String())
	t.Log(crypto.PubkeyToAddress(pubkey).String())
}
```
returns
```
=== RUN   TestCheckKeys
--- PASS: TestCheckKeys (0.00s)
    block_test.go:31: 40a747a10214acebf295760657988b62a75e0bc24a655b68fd606ae5b9b9a61b
    block_test.go:32: 0x57988b62a75e0Bc24a655b68FD606AE5b9B9A61B
PASS
```

```
func PubkeyToIDV4(key *ecdsa.PublicKey) ID {
	e := make([]byte, 64)
	math.ReadBits(key.X, e[:len(e)/2])
	math.ReadBits(key.Y, e[len(e)/2:])
	return ID(crypto.Keccak256Hash(e))
}

func PubkeyToAddress(p ecdsa.PublicKey) common.Address {
	pubBytes := FromECDSAPub(&p)
	return common.BytesToAddress(Keccak256(pubBytes[1:])[12:])
}
```

**Comment by yazzaoui** [comment]
> 1. I didn't get the idea why we need to update `params.ChainConfig`. I could be missing something.
We're not passing `params` but `params.tendermint` when creating the consensus engine https://github.com/clearmatics/autonity/blob/3d4d55029cfb962cb943e0164ad1558363da81a1/eth/backend.go#L252

> 2. I thought about it, but i decided to keep one list.
Ok.

> 3. We can do it. But i think it can introduce more complexity. I decided not to do it now.
Ok, maybe @eastata can give us his point of view?

**Comment by yazzaoui** [comment]
The more I think about it, the more I think we should remove the address field, it's useless..

**Comment by yazzaoui** [comment]
Added missing `minGasPrice` field.

**Comment by yazzaoui** [comment]
Updated issue.

**Comment by Shirikatsu** [comment]
I just spoke to Andres about this. We should probably have a discussion to sync work on this from an identity point of view.

I'll address some points here.

> The more I think about it, the more I think we should remove the address field, it's useless..

I think its very useful. Stake is assigned to an address not a node. This is where we have to be very careful where we're choosing to delineate roles and how they relate to entities.

**Comment by yazzaoui** [comment]
>I think its very useful. Stake is assigned to an address not a node. This is where we have to be very careful where we're choosing to delineate roles and how they relate to entities.

The enode format embeds the public key (nodeid) which is derived the address from, so it's redundant information and potentially conflicting in case of bad configuration.

**Comment by b00ris** [comment]
> I think its very useful. Stake is assigned to an address not a node. This is where we have to be very careful where we're choosing to delineate roles and how they relate to entities.
It's cosmos.sdk's approach. They have separated node key and validation key. I like it, but we are setting node coinbase by node key at the moment. But we might want to keep validation key more secure way(HSM for example) later.

**Comment by yazzaoui** [comment]
Updated issue @Shirikatsu @aesmonty @b00ris

**Comment by Shirikatsu** [comment]
After thinking about this for a while I think this is fine actually for now. (This may also even be fine for the future but more discussion will need to be had).

**Comment by Shirikatsu** [comment]
> But we might want to keep validation key more secure way(HSM for example) later.

So this is what I believe to be the end state. What is our current view on how we will implement interfacing the consensus with a HSM for signing? I am aware of [KMS](https://github.com/tendermint/kms) that can be used with certain HSMs but we may need our own implementation for cloud HSMs.

**Comment by yazzaoui** [comment]
> > But we might want to keep validation key more secure way(HSM for example) later.
> 
> So this is what I believe to be the end state. What is our current view on how we will implement interfacing the consensus with a HSM for signing? I am aware of [KMS](https://github.com/tendermint/kms) that can be used with certain HSMs but we may need our own implementation for cloud HSMs. (Probably a separate discussion about end state though).

Maybe we should create a separate issue for that, or discuss it offline.
