### ISSUE TITLE
[AIP-7] Autonity Contract upgrade mechanism

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#187]
### Preamble 

```
AIP: 7
Title: Autonity Contract Upgrade Mechanism 
Author: Youssef
Type: ASC Standard Track
Category: Core 
Status: Draft
Created: 2019-07-11
```

### Motivation

Proxy contract solutions like OpenZeppelin are either too limited in their capabilities and considered by many not production ready.  The idea of this proposal is to embed into the Autonity protocol a way to perform an Autonity Contract upgrade without hard-forking the client and without using proxy-contracts.

### Specification

The governance account will submit to the Autonity Contract the bytecode, the version and the ABI of a new Autonity Contract and for safety purposes, the bytecode's hash and the ABI's hash as well. The Autonity Contract after checking that the hashes matches, will save into its state memory the new Autonity Contract data.

The Autonity Contract will expose a function to check if an upgrade is ready while the Autonity client will periodically query it after processing every N blocks - I propose N=1 for a start.   

if an upgrade is ready, the client will retrieve the new bytecode and ABI data and retrieve the current state of the Autonity Contract by querying a function. 

Finally, the new Autonity Contract will be deployed at the same address than the old one, and the old state data passed to the constructor.

### Implementation

- Add new field `version` into the Autonity Contract. 
- Add new governance abstracted function to submit to the Autonity Contract a new version of the contract. 
```solidity
function upgradeContract(uint version, bytes bytecode, bytes abi, bytes hashBytecode, bytes hashabi) public governance
```
- The Autonity contract will check if an upgrade is ready by querying:
```solidity
function contractReady() public view (bool)
```
- In the event where a new contract is available, the Autonity Contract will retireve the ABI and the bytecode with :

```solidity
function retrieveContract() public view (uint,bytes, bytes)
``` 
`retrieveContract()` will return the new version, the new bytecode and the new ABI.

- The Autonity contract will also retrieve the current state by querying:
```solidity
function retrieveState() public view returns (DATA)
```

`DATA` here is not a `bytes` field but rather a n-tuple representing the state. Could be for example `DATA = ([]strings, []strings, []strings)` 
- The retrieved state DATA will be passed directly with the same ABI encoding to the new Autonity Contract constructor at deployment: 

 ```solidity
constructor(DATA)
```

**Comment by aesmonty** [comment]
It would be nice to have your view on this @Andreadinenno

**Comment by Andreadinenno** [comment]
Regarding the proposal, as far as i understand here for each update we redeploy a new contract from scratch instead of appending new state variables to the current state, right? My concerns about that are: 

- Waste of gas for deployment, as even for a minimal update all the state needs to be rewritten (but maybe this is not a concern for us). 
- Previous versions of the contract will be lost. With the proxy pattern, we have the ability to switch between versions pretty seamlessly. 

On the other hand, this solution might be less error-prone, as with the proxy pattern there is the risk to overwrite some previous state with new updates.

Regarding ZeppelinOs, i believe that it is ready for production. The team have been working for quite a long time on upgradable patterns before coming up with the proxy solution. All contracts have been audited just like OpenZeppelin ones. There are also few teams already using it on the mainnet - [link](https://forum.zeppelin.solutions/t/using-zeppelinos-framework-on-mainnet-production/598)

What kind of limits have you found out?

**Comment by yazzaoui** [comment]
>Waste of gas for deployment, as even for a minimal update all the state needs to be rewritten (but maybe this is not a concern for us).

Not a problem for us, the governance operator has unlimited ether.

>Previous versions of the contract will be lost. With the proxy pattern, we have the ability to switch between versions pretty seamlessly.

 In my view, not a problem..

Regarding the limitations, there are a bunch of them: https://docs.zeppelinos.org/docs/writing_contracts
The one I find the more particularly annoying is that we can't change the order in which the contract state variables are declared, meaning that once we introduce a state variable then it must stay there at the same place for any subsequent upgrade. Might be okay for the stuff you've been working on but since there will be a lot of differences for the Autonity Contract between 2.0 and 1.5 I'm not so sure if it is suitable.

**Comment by JekaMas** [comment]
It's still not clear when and why we want to use AIP process instead of usual issues.
@yazzaoui

**Comment by yazzaoui** [comment]
> It's still not clear when and why we want to use AIP process instead of usual issues.
> @yazzaoui

I'm working on the workflow with @Shirikatsu, the idea is that we would want using AIP for protocol changes and for major feature requests, not for bug fixes, refactoring and other minor things.

For the reason why, well, we all want to reach high-quality code, implement best programming practice and some features need approval from the product team. AIP will help us achieve those goals and having a  well defined structured way for proposal will permit developers to perform analysis and discuss features at the required technical depth in a systematic manner. 

We need to put in place processes as the team is expanding, they won't be perfect, but we will improve them with time.

**Comment by JekaMas** [comment]
I'm not sure how AIPs could help with the code. Could you explain in details? From my point of view AIP could help to reach agreement between many commands/clients, but it's definitely not the case by the time.

**Comment by yazzaoui** [comment]
All features need to be written into formal specifications using both IEEE SRS and SDD standardization before sign-off from the product team, which is mandatory before execution.
AIP would permit developers to propose new features to be integrated into the specifications.

**Comment by JekaMas** [comment]
Is it a part of clients requirements?
If so it's now more clear. And it's about the clients and capability guarantees not about the code and code quality.

**Comment by yazzaoui** [comment]
>Is it a part of clients requirements?
I guess it's the way the company is operating and why everyone is currently working on documentation instead of code ....

Anyways, as a developper and ultimately being responsible for shipping the product of good quality, I think that a pure waterfall workflow is not fit for what we're working on. There must be a channel for developers to communicate with technical writers and system designers. 
I think AIP can help and it's as well about code quality because with the "implementation" section it would help us discuss how the feature could be implemented in practice..

**Comment by yazzaoui** [comment]
closing, implemented.
