### ISSUE TITLE
Review potential DoS backlog vulnerability Byz Proposer in handleProposal()

### ISSUE THREAD

**Issue by aesmonty** [clearmatics/autonity#194]
Investigate potential vulnerability in `handleProposal(...)` in `consensus/tendermint/core/propose.go. 

The `handleProposal` logic have been ported directly from `IBFT` implementation, but it would be good if we double-check that there is no security leak here.

## Description

In `handleProposal(...)` we just check if the proposal comes from the valid proposer for that round. If that proposal is future (in `time `field, not in `view`), we will store it in our backlog. However, we are not checking if we have already received a proposal from the proposer. Therefore, a byzantine proposer might be able to populate the backlog of other nodes with many future proposals for the same round.

**Comment by yazzaoui** [comment]
seem depreciated, closing
