### ISSUE TITLE
Define all required tests for Tendermint

### ISSUE THREAD

**Issue by aneequesafdar** [clearmatics/autonity#217]
related to #213 #214 #215 #216. We need to determine what test cases we need to test for Tendermint implementation and have a view on how to implement them.

**Comment by JekaMas** [comment]
@aneequesafdar do we need this issue?

**Comment by aneequesafdar** [comment]
Yes, once I have reviewed your pull request, I will enumerate some test cases by going through the Tendermint repo.

**Comment by JekaMas** [comment]
So I think we can close.

**Comment by JekaMas** [comment]
wont need
