### ISSUE TITLE
Consensus restart after more than f nodes crash

### ISSUE THREAD

**Issue by aneequesafdar** [clearmatics/autonity#237]
# Problem

The Tendermint implementation should be able to restart after more than f (some of which will be honest) nodes which go down. The assumption was made that not more than f nodes will be faulty, however, in a real network, honest nodes may take long to connect or crash, this should not have an impact on consensus. Therefore, we need to have a mechanism for the consensus to restart once honest nodes are online after a crash.

# Implementation

Use basic WAL to send messages to peers when network is stuck due to more than f nodes crash,

# Acceptance Criteria

- Tests from https://github.com/clearmatics/autonity/issues/237 should be restored and `green`
- Manually test on aws cluster tendermint can restart after more than f nodes crash

**Comment by b00ris** [comment]
closed by https://github.com/clearmatics/autonity/pull/243
