### ISSUE TITLE
RPC tendermint_GetContractAddress

### ISSUE THREAD

**Issue by eastata** [clearmatics/autonity#320]
# Problem

autonity deployed with flag:
```
--rpcapi eth,web3,net,txpool,tendermint,debug
```
Network is working and mine blocks
Trying to get autonity contract address:
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"tendermint_GetContractAddress","params":[],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method tendermint_GetContractAddress does not exist/is not available"}}
```
But the same time `tendermint_getWhitelist` is available and method response is correct

When connect to console I have found that avalable only next methods for `tendermint`:
```json
  getGlienickeContractABI: function(),
  getGlienickeContractAddress: function(),
  getSomaContractABI: function(),
  getSomaContractAddress: function(),
  getValidators: function(),
  getValidatorsAtHash: function(),
  getWhitelist: function()
```
# Version
* `v0.2.1`
* current [master branch](https://github.com/clearmatics/autonity/tree/63ef0893a28dc1831ef9f0bddd0d00f8624a3f62)

# Acceptance Criteria

* Any way how to get this address using RPC

# Notes

Blocker for https://github.com/clearmatics/charts-ose/issues/106

# Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by aesmonty** [comment]
There is an error in the query, it should be `tendermint_getContractAddress`. Could you check if this was the cause of the issue? @eastata 
```
andres@cl:~/go/src/github.com/clearmatics/dep$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"tendermint_getContractAddress","id":1}' http://127.0.0.1:6000
{"jsonrpc":"2.0","id":1,"result":"0xe536720791a7dadbebdbcd8c8546fb0791a11901"}

```

**Comment by eastata** [comment]
Thanks @aesmonty Is any place where it defined?

**Comment by aesmonty** [comment]
I don't think (as far as I know). I am working now on improving that :+1:
