### ISSUE TITLE
Autonity HelloWorld, Autonity Wiki, or both?

### ISSUE THREAD

**Issue by aesmonty** [clearmatics/autonity#325]
# Problem

I have extended the RPC API and been requested by @yazzaoui and @JekaMas to update the docs to reflect the changes. The problem is that I have been pointed to two different files:

- https://github.com/clearmatics/autonity/blob/master/helloworld/README.md
- https://github.com/clearmatics/autonity/wiki/Autonity-Contract

Both are quite outdated (especially the Helloworld one, which was last updated in April). I would like to have your views on which one is our source of truth and if we are aiming to maintain both. @shapeshed @yazzaoui @JekaMas 

@eastata also has requested the most updated version of web3 and RPC methods.

**Comment by shapeshed** [comment]
Suggest connecting with the product team here since documentation is now owned there.

There is docs.autonity.io, the wiki and also README files within folders. The Product Team should decalre user facing documentation should go. I would advocate docs.autonity.io.

**Comment by maxcroasdale** [comment]
My vote is for docs.autonity.io to be the single source of truth.

**Comment by shapeshed** [comment]
Thanks let's do that.

@aesmonty -> https://github.com/clearmatics/autonity-docs/

**Comment by yazzaoui** [comment]
Closing this issue
