### ISSUE TITLE
Tendermint core-backend re-architecture

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#326]
## Tendermint core-backend re-architecture

- Backend should have a reference of core instead of the opposite. All functions called from the rest of the codebase should be directed to backend implementing `Engine`.
If this architecture is difficult to realise then I suggest merging core and backend and creating a single package.

- Drop complete support from clique and ethash: This system is designed around the BFT consensus engines at its core and statements like `if h, ok: = w.engine.(consensus.Handler);` that clutter the rest of the codebase have no reason to exists. As a consequence, we can merge the `BFT` and `Handler` interfaces with `Engine` .

- This task is now high priority, it will need to be done one day so better to do it now.

**Comment by JekaMas** [comment]
Maybe we should do it another way: write down all the functionality, group it, write schemes and then do refactoring? Maybe we need to rewrite everything as a stateless state machine for further verification.

For me, it won't change much if we do the refactoring as it's described in the issue
