### ISSUE TITLE
Extradata vs block header updates for Pos

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#343]
In order to support omission-fault accountability, fix a vulnerability with missing round information add voting power support, we have to add new fields into the block header structure. For that we have 2 options:

### Option 1 - Update extradata

```golang
type BFTExtra struct {
	Validators        []common.Address
	VotingPower       []*big.Int
	Seal              []byte
	Round             []*big.Int
	CommittedSeal     [][]byte
	PastCommittedSeal [][]byte
}
```
And we should rename this struct to _POSBFTextra_ to make things clear.

### Option 2 - Update block header 
The proposal is to add those new fields directly into the block header structure :

```golang
type Header struct {
	ParentHash        common.Hash       `json:"parentHash"   
	UncleHash         common.Hash       `json:"sha3Uncles"    
	Coinbase          common.Address    `json:"miner"     
	Root              common.Hash       `json:"stateRoot"   
	TxHash            common.Hash       `json:"transactionsRoot" 
	ReceiptHash       common.Hash       `json:"receiptsRoot"   
	Bloom             Bloom             `json:"logsBloom"        
	Difficulty        *big.Int          `json:"difficulty"      
	Number            *big.Int          `json:"number"      
	GasLimit          uint64            `json:"gasLimit"         
	GasUsed           uint64            `json:"gasUsed"          
	Time              uint64            `json:"timestamp"   
	Extra             []byte            `json:"extraData"      
	Validators        []common.Address  `json:"validators"   
	VotingPower       []*big.Int        `json:"votingPower"   
	Seal              []byte            `json:"seal"   
	Round             []*big.Int        `json:"round"   
	CommittedSeal     [][]byte          `json:"committedSeal"   
	PastCommittedSeal [][]byte          `json:"pastCommittedSeal"   
	MixDigest         common.Hash       `json:"mixHash"`
	Nonce             BlockNonce        `json:"nonce"`
}
```

This would lead to a cleaner design.

**Comment by Shirikatsu** [comment]
HEAVILY in favour of option 1.

Multiple reasons:
* Modifying block header will REALLY diverge us from upstream.
* This affects Ion interop and means that that will have to be maintained separately to Ethereum interop
* Consensus stuff should not bleed into core data structure stuff.

**Comment by yazzaoui** [comment]
>Modifying block header will REALLY diverge us from upstream.

We have to do it in a way or another, the proposal is to remove one level of nesting in order to make fields more accessible for various low-level technical reasons. Not sure if we will diverge that much from upstream by doing that, can you precise your point? 

 >This affects Ion interop and means that that will have to be maintained separately to Ethereum interop

Can you explain more please?

>Consensus stuff should not bleed into core data structure stuff.

Consensus is the kernel of the system where everything else is built around, so not sure if this argument is valid . BTW we already have `Nonce`, `Difficulty`, `UncleHash` which are heavily linked to pow.

**Comment by yazzaoui** [comment]
closed via https://github.com/clearmatics/autonity/pull/359
