### ISSUE TITLE
Include Chain ID opcode

### ISSUE THREAD

**Issue by Shirikatsu** [clearmatics/autonity#345]
# Problem

The CHAINID opcode present in Geth `1.9.2` would be very useful in Autonity.

This will allow Ion and CMF projects to utilise inherent blockchain data to identify chains as opposed to arguments passed to smart contracts.

# Implementation

Merge Geth 1.9.2 into Autonity.

# Acceptance Criteria

Chain ID opcode, when executed should return the correct Chain ID as specified in the genesis file.

**Comment by yazzaoui** [comment]
Closed by https://github.com/clearmatics/autonity/pull/367
