### ISSUE TITLE
Keep header structure changed but encode all the changes into extradata field

### ISSUE THREAD

**Issue by JekaMas** [clearmatics/autonity#371]
It's about custom encoder and decoder maybe with additional tag for the structure. It'll help us to keep all the changes and don't have to perform hard forks if header is changed.

**Comment by JekaMas** [comment]
@yazzaoui How do you thing could we use golang tags to version header structure?

**Comment by yazzaoui** [comment]
I would rather add a new field `version` in the header structure which will be populated by `DecodeRLP` somehow. I think that we will still need to hardcode somehow a mapping `blockNumber =>  version` to know which final struct to use and if we want to stay generic as possible we would have to create a `header` interface.
This seems to be a lot of work for uncertain gains ?

**Comment by JekaMas** [comment]
Ok, so going to implement without versioning.
