### ISSUE TITLE
Reduce the volume of logging data produced by the Autonity client

### ISSUE THREAD

**Issue by p1747150** [clearmatics/autonity#428]
# Problem

In the context of SystemX, the volume of logging data being produced by the AFNC is extremely large due to the fact that the majority of log data is created with a log level of DEBUG or INFO.

The high volume of log data being produced will impact the ability to effectively troubleshoot issues in a live production environment.

# Implementation

By default, I would expect the AFNC to only log messages with a level of WARN or ERROR unless the AFNC has been specifically configured to output DEBUG or INFO level messages.

# Acceptance Criteria

Check volume and level of messages being created by AFNC.

# Notes

The purpose of this issue is to gain an understanding of the effort required in order to better control the volume of AFNC logging.

# Future Steps

Review volume of logging data from the AFNC for SystemX.

**Comment by yazzaoui** [comment]
Hello,

You can set up the logging level with the `--verbosity` command line flag. 
`DEBUG` and `INFO` logs are extremely helpful for us to troubleshoot consensus issues, and we would not be able to perform any investigations without them.
So instead of reducing the level could you maybe prune old logs messages, let say >X days?

**Comment by p1747150** [comment]
We can certainly discard/purge logs after a number of days, however we may need to keep data for up to 30 days (possibly longer) for audit/regulatory reasons which will result in a large volume of data having to be stored and indexed. Also due to the volume of log data being produced by the AFNC, our log monitoring dashboard (Kibana) becomes very noisy.

If not possible/recommended to reduce log level of the AFNC we may need to consider filtering/discarding logs at source (by fluentd) prior to forwarding to Elasticsearch/Kibana as an alternative.

**Comment by yazzaoui** [comment]
Won't fix, closing
