### ISSUE TITLE
Test maximum participants with current full-mesh topology 

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#437]
# Problem

ASC requirements is to have :
- A fully connected graph between committee members.
- Participants/stakeholders should be connected to least 1/3 of the total voting power.
  
For the time being, we are enforcing a fully connected graph between every participant on the system, which is satisfying the requirements but is not a very scalable approach. Before implementing more complex logic we need to have a better understanding of how many participants can we support using our current approach.

# Plan
In current default full-mesh network topology, we need to measure the up boundery of the network under which block producing, and TX issuing is still working with a reasonable response. Beside this, we need to consider how the network delay might impact the network's distributed coordination under the up boundery.

### option1: Google compute nodes
We have python e2e test engine which can deploy network by using ssh session. We can add new features: get IP list from google dashboard, generate meta data, prepare script to issue TXs  from each node, collecting block producing rate, and TX accepted rate from each node.

### option2: Google K8s Engine
This is the tool chain used by DEVOP team, and DEVOP have such tools to deploy network but had never test it with 100 or 200 nodes yet. And this infrastructure is under the same data center at London, within 10 ms delay from each host, can hardly test the delay from different data center.
Mean while, we also need to deploy script to simulate TX and collecting data as the report.

## Collect test reports
Different Network size (50, 100, 150, 200, etc...), same data center, cross data center [EU, HK, USA] untill we address the boundery.
Chain performance, block producing interval, TX TPL.
Prometheus TSDB will be used to fetch performance metrics from the nodes.

**Comment by Jason-Zhangxin-Chen** [comment]
[Autonity 1.0.0 Scalability Test Report.pdf](https://github.com/clearmatics/autonity/files/4323607/Autonity.1.0.0.Scalability.Test.Report.pdf)

**Comment by Jason-Zhangxin-Chen** [comment]
[Autonity 1.0.0 Scalability Test Report V0.0.2.pdf](https://github.com/clearmatics/autonity/files/4401688/Autonity.1.0.0.Scalability.Test.Report.V0.0.2.pdf)

**Comment by Jason-Zhangxin-Chen** [comment]
@yazzaoui @JekaMas @b00ris @screwyprof  @aneequesafdar @differentialderek @piersy 
The network scalability testing report was attached here. In the V0.0.2 version, we add a new test set, which increase the number of participant and measures the related metrics. Please have a review on it. Thanks.

**Comment by Jason-Zhangxin-Chen** [comment]
[Autonity 1.0.0 Scalability Test Report V0.0.3.pdf](https://github.com/clearmatics/autonity/files/4414253/Autonity.1.0.0.Scalability.Test.Report.V0.0.3.pdf)

@yazzaoui @JekaMas @b00ris @screwyprof @aneequesafdar @differentialderek @piersy
The network scalability testing report was attached here. In the V0.0.3 version, we add 2 new testcase in TESTSet4, which keep the number of validators to 12 and 15, then keep 100 participants. When we have a validator set at range [4, 15] with a 100 paricipants, increasing the computing power does not help to improve the throughput, and the TPS of the network will hit at range [200, 300] as we address at CASE2 at the same TESTSet4.
