### ISSUE TITLE
Duplicate entries in whitelist

### ISSUE THREAD

**Issue by raj-shekhar1** [clearmatics/autonity#450]
# Problem
Duplicate entries in the white list while adding the nodes.
Scenario- Added node as participant and after full sync added(promoted) it as validator.

An overview of the background required to understand the problem.

# Implementation

#### Explain how did you retrieve the white list data.
Using system console api.

#### how did you interact with the autonity contract, was it with some integration tool or direct RPC calls? 
 Using system console api.

#### can you systematically reproduce the issue? 
Yes, deploy node, add it as participant, after full sync, promote/add it to/as validator. Then check the white list it contains duplicate entries of the newly added node.
 

# Acceptance Criteria
There should be no duplicate entries in the whitelist.
Rules for the future PR to be accepted.

# Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

# Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by yazzaoui** [comment]
solved, closing.
