### ISSUE TITLE
Consensus is stuck when an invalid enode is added.

### ISSUE THREAD

**Issue by screwyprof** [clearmatics/autonity#451]
## How to reproduce
1. `git checkout develop`
2. `make autonity`
3. Deploy a network of 4 nodes:
`./main.py /home/ya/dev/autonity/build/bin/autonity -n 4`
4. Make sure mining works and new blocks are minted.
5. Add a random node via console:
`autonity.addParticipant("0xb605e98649Fb40256d73f6C321cFa399BB6534CD", "enode://e7507c6c67d1307010e7ffb07a572b868b5dc65bc264ccbdcd94c0ff8d9023c25eb090b1dd5ef9948bb9847c506452c204b37187aa4954cbc06592a8358abb94@127.0.0.1:8527", {from: eth.accounts[0], gasPrice:500000})`

## Current behaviour
Consensus is stuck.  The invalid nodes are being parsed many times (the attempts messages are duplicated)

## Expected behaviour
If a new validator is being added and parsed unsuccessfully, the consensus should  be still functioning given that a quorum (2/3 of the network) is still well-behaving.

**Comment by piersy** [comment]
We are facing this issue again

**Comment by piersy** [comment]
Actually we were not facing this issue, again.

We added an unreachable validator to a the network spun up by `local-autonity-deployment-utility`  with the following call.
```js
autonity.addValidator(
    "0x850C1Eb8D190e05845ad7F84ac95a318C8AaB07f", 
    2000, 
    "enode://d73b857969c86415c0c000371bcebd9ed3cca6c376032b3f65e58e9e2b79276fbc6f59eb1e22fcd6356ab95f42a666f70afd4985933bd8f3e05beb1a2bf8fdde@172.25.0.11:30303",
    {from:eth.accounts[0], gasPrice:500000}
```

This adds a validator with 2000 stake, but the `local-autonity-deployment-utility` network only starts with 5 stake in total. So nodes were not able to form a quorum and so blocks correctly stopped being produced.
