### ISSUE TITLE
Create a plan for updating the Autonity documentation

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#461]
# Problem

We don't know have a clear idea of which areas of the [autonity docs](https://github.com/clearmatics/autonity-docs-v2) are are lacking.

We don't know the relative importance of different areas of the documentation, so we cannot prioritise documentation.

We don't have a process for creating documentation.
 
# Acceptance Criteria

Write up a plan discussing how to address these issues.

**Comment by SherifSK** [comment]
My understanding is that @maxcroasdale started this effort with the Engineering team members a while back using Hyperledger Besu as a starting point i.e. a table of content.

Hyperledger Besu docs has the following table of content (ToC):

1. How to
2. Tutorials
3. Concepts
4. Reference (developer docs)

(Hyperledger team apparently have read this great [article](https://www.divio.com/blog/documentation/) and following its breakdown of documentation)

I think we should differentiate between:
- User docs (items 1, 2 and 3 in the above ToC)
- Developer docs (item 4)

I think User Docs currently has a higher priority to address the requirements for Q1 and Q2 releases (focus on System X). Based on this understanding (which I am happy to change or have it challenged), I directed @maxcroasdale to use for the How To section of the docs the how-to guides (as a base) that were developed/undergoing development by Ben and Frank as part of their SystemX work (specifically the how-to guides developed early on as they were only using the AFNC i.e. no System Console).

IMHO, the order of priority of the above ToC should be:

1. How to
2. Concepts
3. Tutorials
4. Reference

However, despite all of the above efforts I think the right approach to designing a successful documentation experience is to start from a UX perspective by creating user personas and then creating user stories/journey/epics and try to understand properly what should be included (and why) and how i.e. information design. The question is bandwidth vs. time available. I think this should be discussed with @yazzaoui.

**Comment by saronimo** [comment]
I;m pleased to see this is being dedicated time, but would echo @SherifSK in saying that a lot of work has already gone into thinking about this and what we really need now in content from the team who built autonity! 💪 

What can we do to help?

**Comment by piersy** [comment]
@SherifSK @saronimo Thanks for the feedback, lets schedule a meeting where you could bring me up to speed with the current situation from your perspective.

**Comment by saronimo** [comment]
Ok please set something up later as this is a very high priority given our timelines and please invite @maxcroasdale as well

**Comment by piersy** [comment]
@saronimo @SherifSK @maxcroasdale As per our discussion:

We are following the documentation approach/structure used by [hyperledger besu ](https://besu.hyperledger.org/en/stable/). 

They have 4 top level headings which we are assigning the following priorities. Our target readers are ether a tech savvy user or developer. The first tech savvy users will most likely be paying customers.

1. How To (straight to the point guides to get users from A to B)
1. Reference (developer API reference, we envisage that most developers referring to this documentation will be part of the open source community, we wan't this doc to be good to foster community uptake of autonity) 
1. Concepts (help provide a deeper understanding of the application) 
1. Tutorials (Similar to "How To" but more in depth)

We have a preliminary TOC clearmatics/autonity-docs-v2#16 and @saronimo provided a high level list of features required for the Q1 release.  We can take the intersection of these to find the topics that need documenting. 

Max has been working on How To guides which hopefully will cover what we see needs documenting from the intersection of features list and the TOC. These guides need to be reviewed. 

We want to have 2 levels of review for docs
1. Technical - Developers check that the doc is accurate.
1. Language/Ontology - Relevant teams check documentation for style/readability.

I (@piersy) need to check existing reference docs in the old docs [repo](https://github.com/clearmatics/autonity-docs) and see if any are fit to be pulled across into the new docs repo, and check the status of all Concepts [issues](https://github.com/clearmatics/autonity-docs-v2/issues?q=is%3Aissue+is%3Aopen+Concepts) in the new docs repo and if any have had any work done on them follow up with the authors to ensure that the documentation is up to date.

**Comment by piersy** [comment]
After discussions with @maxcroasdale this morning we decided to move documentation into the autonity repo because that will make it much easier to ensure that documentation and code are kept in sync.

We are starting to document from an empty Sphinx framework, see - clearmatics/autonity-docs-v2#18

**Comment by piersy** [comment]
This is the list of features that are expected for this release. We want to documents the topics that form the intersection of these features and the TOC defined here clearmatics/autonity-docs-v2#16.

**Autonity API**
JSON RPC API that exposes on-chain functionality. Provides:
* Ethereum JSON RPC API
* Autonity namespace extension for returning Autonity Protocol state.

**Consensus Module (BFT)**
The Consensus Module implements the Tendermint consensus protocol:
* Byzantine Fault-Tolerant state machine replication (BFT-SMR)
* Block proposal and validation by cryptographic identities permissioned to participate in consensus rounds


**Runtime Computing Environment**
A State Transition Function providing the execution environment for transaction processing and computing bounded by Ethereum gas model.
* Execution model that specifies how the system state is changed given a series of bytecode instructions and environmental data, implementing the Ethereum Virtual Machine (EVM) OPCODE set
* Execution runtime applies transaction and verifies it forms a valid transition between pre- and post- transaction state.


**Data Storage**
LevelDB storage of system state as Modified Merkle Patricia Trie data structures.

**P2P Networking**
Peer-to-Peer networking between Autonity Clients:
* devp2p networking protocol (RLPx, Ethereum Wire Protocol)


**Metrics APIs**
Provides both push and pull metrics collection interfaces. Collected metrics are exposed to HTTP endpoints for:
* Prometheus (pull based monitoring mechanism)
* InfluxDB (push based monitoring mechanism)

**Peer Node List**
The Autonity Client maintains a dynamic list of current peer nodes

**Validator  List**
Maintains a list of the cryptographic identities forming the validator set

**Gas Management**
Calculation and distribution of gas fee as per the Ethereum protocol. For each block, the Autonity Protocol deducts transaction processing cost from transaction submitter’s intrinsic account balance

* Configuration via the JSON-RPC API:
  * Mint
  * Burn
  * Distribution

**Comment by piersy** [comment]
For ease of comparison I'm copying the TOC here.

| Section          | Topic                             | Q1 | Q2 |
|------------------|-----------------------------------|----|----|
| Getting Started  | Sys Reqs                          |    |    |
|                  | Install Binary (local)            |  y   |    |
|                  | Install to GCloud - kube/helm etc |  y  |    |
|                  | Join an existing network          | y   |    |
| Configure        | Consensus Protocols               |    |    |
|                  | Generate Genesis File             |  y  |    |
|                  | ?Configuration file?              |    |    |
|                  | ?Configure Mining?                |    |    |
| Interact         | APIs                              |    |    |
|                  | Access APIs                       |    |    |
|                  | ?What protocol procedures/calls?                 |    |    |
|                  | Authentication and Authorization  | y   |    |
|                  | Client libraries                  |    |    |
|                  | Filter - accessing                |    |    |
|                  | Find and connect to nodes         |    |    |
|                  | any other interaction with nodes  |    |    |
| Monitoring       | use metrics                       |    |    |
|                  | configure logging                 |    |    |
| Transacting      | get a balance/get a fee           | y   |    |
|                  | Create and send                   |  y  |    |
| Permissioning    | ???                               |    |    |
| Privacy features | ???                               |    |    |
| Housekeeping     | ?data backup and restore?         |    |    |
| Network upgrade  | method and versioning             |    |    |
| Developing DApps |                                   |    |    |
| Troubleshooting  | Solving common problems           |    |    |
|                  |                                   |    |    |
| Concepts         | Architecture                      |    |    |
|                  | Consensus Protocols               |    |    |
|                  | Client Libraries                  |    |    |
|                  | Privacy                           |    |    |
|                  | Permissioning                     |    |    |
|                  | Pruning                           |    |    |
|                  | Transactions                      |    |    |
|                  | Monitoring                        |    |    |
|                  | Events and logs                   |    |    |
|                  | Mining                            |    |    |
| Reference        | CLI                               |    |    |
|                  | API Methods                       |    |    |
|                  | Genesis File                      |    |    |
|                  | Account for testing               |    |    |
|                  |                                   |    |    |
| Tutorials        | Create a network                  |    |    |
|                  | Create a network - using PoW                         |    |    |
|                  | Create a network - using PoA                         |    |    |
|                  | Create a permissioned network     |    |    |
|                  | Create a privacy enabled network  |    |    |

**Comment by SherifSK** [comment]
@piersy, Please note that this ToC doesn't reflect the entirety of the Hyperledger Besu ToC and also neglects the main sections i.e. How To, Tutorials, Reference and Concepts.

**Comment by piersy** [comment]
Now I'm going to take my previous categorisation of features under main documentation headings and intersect those with the TOC to find what needs documenting for this release.

The categorisation of features was.

* How to
* Reference
  * Autonity API
  * Metrics APIs
  * Configuration via the JSON-RPC API _(this might be documented by geth in whic case we don't need to here)_
* Concepts
  * Consensus Module (BFT)
* Tutorials

Notably the features don't warrant any howto guides, so I'm wondering how we define the list of things that a user wants to do with the system, such that we can derive the relevant howto guides for this release? @maxcroasdale @saronimo @SherifSK 

When we intersect the categorisation of features with the TOC, we get the following, which is not much to document.


| Section          | Topic                             | Q1 | Q2 |
|------------------|-----------------------------------|----|----|
| Interact         | APIs                              |    |    |
|                  | Access APIs                       |    |    |
| Monitoring       | use metrics                       |    |    |
| Concepts         |  Consensus Protocols                       |    |    |
| Reference        | API Methods                               |    |    |

**Comment by SherifSK** [comment]
> Now I'm going to take my previous categorisation of features under main documentation headings and intersect those with the TOC to find what needs documenting for this release.

What is the previous categorisation? Where did this come from? I think we should stick to mapping the ToC with the Features from @saronimo.

**Comment by piersy** [comment]
@SherifSK 
> What is the previous categorisation? Where did this come from?

It came from a previous comment, I added a link to clarify where it came from.

 > I think we should stick to mapping the ToC with the Features from @saronimo.

What I tried to do was intersect the TOC with the Features from @saronimo

**Comment by piersy** [comment]
I tried to map the features from @saronimo to the headings found in the [full hyperledger besu TOC](https://github.com/hyperledger/besu-docs/blob/8e00ed73c5ecd8588c4ac9fefab95951fcfbbb31/mkdocs.yml#L55) in a single [table](https://docs.google.com/spreadsheets/d/1syabbcOuGmj5VxWHQRDNfLBzcr6O56-l6wH_njjonYk/edit?usp=sharing).

The process of mapping from features to documentation is not always straightforward and the result (below) is that some areas seem to have a lot of focus whilst other sections that I would expect to see in the documentation are completely empty. Also I think a lot of the hyperledger besu headings are too specific to really apply to our situation.

```
How To -> Find and connect to Peers -> Configure Ports for Access
How To -> Find and connect to Peers -> Configure Static Nodes
How To -> Find and connect to Peers -> Manage Peers
How To -> Find and connect to Peers -> Specify NAT method
How To -> Find and connect to Peers -> Speficy Bootnodes
How To -> Configure -> Configure a Free Gas Network
How To -> Configure -> Consensus Protocols -> Tendermint
How To -> Interact with Node -> APIs -> Acess APIs
How To -> Interact with Node -> APIs -> Authenticate JSON-RPC Requests
How To -> Interact with Node -> APIs -> Use JSON-RPC API over HTTP or WebSockets
How To -> Interact with Node -> Filters -> Access Logs Using JSON-RPC API
How To -> Monitor Nodes -> Use Metrics
Reference -> API Methods
Reference -> API Objects
Concepts -> Consensus Protocols -> Tendermint
```
I don't think the above approach is going to provide cohesive documentation for a user, but rather fragmented and difficult to follow documentation.

Given the problems with that approach, I'm going to have a stab at defining a set of headings that hopefully provide a cohesive set of documentation for users that covers what they want to do and the features in this release. I'll keep it relatively high level since I don't know much about the details of autonity, these topics may get split into further subtopics when I've got a bit more knowledge about the internals.

```
How To -> Run a node (covers build, install, config, running)
How To -> Run a network (covers configuring operator, participants, validators)
How To -> Deploy a contract
How To -> Access JSON-RPC API
How To -> Access Metrics API
Reference -> JSON-RPC API
Reference -> Metrics API
Concepts -> Tendermint Consensus
```
@maxcroasdale @saronimo @SherifSK Please let me know if you think there are any missing/extraneous topics here, thanks.

**Comment by maxcroasdale** [comment]
These headings look practical and thorough for an initial release.

**Comment by maxcroasdale** [comment]
comment

**Comment by piersy** [comment]
@maxcroasdale @SherifSK @saronimo 
I'm assuming that we are happy with the following set of headings.
```
How To -> Run a node (covers build, install, config, running)
How To -> Run a network (covers configuring operator, participants, validators)
How To -> Deploy a contract
How To -> Access JSON-RPC API
How To -> Access Metrics API
Reference -> JSON-RPC API
Reference -> Metrics API
Concepts -> Tendermint Consensus
```

The plan in order to generate the content for these is as follows.

1. For me to actually use autonity (run, deploy, use the apis)
2. For me to generate documentation for a couple of the headings.
3. Review the documentation with @maxcroasdale  and make any adjustments.
4. Seek contributions from other members of the autonity team who can use initial docs as a guide to the style/approach to use.
5. Have the relevant teams review those contributions.

At that point we can just keep repeating steps 4 and 5 until everything is done.
