### ISSUE TITLE
Research: What To Do With a User's ETH When They're Removed

### ISSUE THREAD

**Issue by differentialderek** [clearmatics/autonity#467]
# Problem

If a user owning ETH is removed, either by choice or because they've been slashed, we can either burn their ETH or distribute it among current validators. Both have their pros and cons. This issue is  for a report that suggests we burn the ETH, distribute it among current validators, or something else.

# Implementation

The deliverable here is a report with a recommended strategy, with justification and references.

# Acceptance Criteria

The report should be compelling and thorough, with a clear recommendation that can be implemented.

# Notes

Different blockchains have different stances on this issue. It would be nice to include references to those here, detailing what similarities/differences we might have with them that would make us go one way or the other.

# Future Steps

Implement the spec from this issue.

**Comment by yazzaoui** [comment]
My view is that we shouldn't design a mechanism to remove ETH automatically. It's easy for a validator to transfer his eth to any account before getting slashed or removed, so what do we do in this case? On the contrary of the stake token there is no permissionning feature implemented at this level so it makes it even harder. 
Looking to me as a technical and legal rabbit hole to remove ETH from the system.

> ETH is removed, either by choice or because they've been slashed

Can you precise what you mean "by choice"?  There is no such functionally to burn ETH implemented?

**Comment by differentialderek** [comment]
> Can you precise what you mean "by choice"?

Looking at it again, the "by choice" bit shouldn't be in there. I had a mental model of users being able to delete accounts, but in Ethereum (and presumably here) accounts are permanent addresses, so a user leaving "by choice" doesn't really make sense.

I guess the main question here is what to do with a user's ETH if they get slashed from the network. (This assumes that we'll be slashing at all.)

**Comment by flofrie** [comment]
Glad this is closed. fundamentally, a user cannot be "removed". As long as they have a private key, and can send Tx to the System, they can move their E. (Also, please, let's stick to "E" or "native account coin") -- Any implementation to the contrary is wrong.

If someone loses access (e.g. the lose their private key, or lose their ability to send Tx to a Node on the System), then that's entirely their problem. There certainly must not be any automatism.

I don't understand how slashing appears in this context. If someone's stake gets slashed, it has absolutely no impact on their holdings of E, or their access to it. (Certainly, Participants that are not Validators, will have no stake, but do hold E, and can freely use it.)
