### ISSUE TITLE
Autonity client should exit if started without config file and database

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#473]
# Problem

It's possible to run the autonity client without a config file and without a db, this should be forbidden.

# Acceptance Criteria

When run without a config file and db the autonity client should exit with a non 0 exit code and display a message explaining that a config file argument must be provided in order for it to function correctly.

**Comment by JekaMas** [comment]
It's possible to run the node without the config and it shouldn't be an error. After a first start with the config, it should be stored in the DB so user doesn't need to specify it again.

**Comment by piersy** [comment]
@JekaMas I'm pretty sure I am able to run the client without config on the first start.

**Comment by piersy** [comment]
I cant see a way to satisfy the tests in cmd/autonity without fully re-writing them. The tests rely on scraping the log output of the command and so are totally brittle.

**Comment by Jason-Zhangxin-Chen** [comment]
Yes, there are some testcase which is kind of log parser for the expected console prints.

**Comment by piersy** [comment]
So I found a way to satisfy the tests, they are really horrible though, very convoluted and brittle, over fitting what needs to be tested.

I'm now blocked becuase I need fixes from #552 in order to solve the final problems I encountered.

**Comment by yazzaoui** [comment]
superseded by https://github.com/clearmatics/autonity/issues/682
