### ISSUE TITLE
Consider not using ci.go in our CI config

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#474]
# Problem

We use `ci.go` in our github actions build job and we don't actually need to.

The problem with `ci.go` is that it obscures what command is actually going to be run, and in order to understand what a `ci.go` command does you need to follow its code where it builds up a commandline in a piecemeal fashion and then executes it. It adds flags to the command seemingly arbitrarily and it is not well documented. This adds a lot of overhead when trying to understand what our CI is doing. The code is ~2000 lines, which doesn't justify the effect, which in this case is to add flags of the following form.

```
-ldflags "-X main.gitCommit=e3f963b9090bf75368e01b25e2fa62ad5a40baf5 -X main.gitDate=20200316"
```

If we want to embed commit hash and commit date into our binaries (which I think is a good idea) then we can achieve that in a much more straightforward fashion. We can use the following scripts to grab the commit and date and then use command substitution to generate the flags. 

`commit.sh:`
```
#!/bin/bash
git rev-parse HEAD
```
`commit_date.sh:`
```
#!/bin/bash
git show -s  --date=format:'%Y%m%d' --format=%cd HEAD
```
```
-ldflags "-X main.gitCommit=$(./commit.sh) -X main.gitDate=$(./commit_date.sh)
```

# Acceptance Criteria

Remove use of `ci.go` from our CI config.

**Comment by JekaMas** [comment]
As far as I can see `install` command is quite complicated. It contains special cases for different architectures and C compiler (autonity uses C).
We can replace it with a simple command, however, we'll lose capability with different platforms. It seems we need guys from business and/or project management.
@yazzaoui

**Comment by piersy** [comment]
This ticket has been superseded by #505
