### ISSUE TITLE
Behaviour tests for Tendermint Core

### ISSUE THREAD

**Issue by aneequesafdar** [clearmatics/autonity#480]
# Problem

Currently, there are few or very little tests which explicitly test the behaviour of Tendermint's `upon conditions` as defined on page 6 of [The latest gossip on BFT consensus](https://arxiv.org/pdf/1807.04938.pdf). In order to gain further confidence in our implementation, we need to add these behaviour tests. 

# Implementation

Enumerate all different possible inputs to upon conditions and ensure the correct behaviour is express in the new tests.

# Acceptance Criteria

All new and old tests must pass.

**Comment by JekaMas** [comment]
Is it possible to 'Enumerate all different possible inputs to upon conditions '? For me, It sounds more like model checking than e2e tests.

**Comment by aneequesafdar** [comment]
I think enumerating all different possible state is model checking, which I think is different from checking all different inputs for upon conditions. The model checking is in the pipeline for later.

**Comment by aneequesafdar** [comment]
reopen later when more test cases to write
