### ISSUE TITLE
Add Makefile to clearmatics/local-autonity-deployment-utility

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#485]
# Problem

It's a bit fiddly to work out how to use the local-autonity-deployment-utility and subsequently remember the sequence commands you need to use it. We can encapsulate this in a Makefile which should make the project easier to use.

# Acceptance Criteria

Add a Makefile that in one step can build autonity, install python dependencies of the project and run a local network.

**Comment by JekaMas** [comment]
For me, we shouldn't support this utility at all, but write e2e tests or deploy kubernates cluster if needed.
