### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#496]
# Problem

The following tests fail randomly. I provide links to the failures all the links are related to commit c37a10a. It can be seen that all of these tests have passed in some of the runs.

```
TestContractUpgradeSeveralUpgrades
https://github.com/clearmatics/autonity/runs/588448483
https://github.com/clearmatics/autonity/runs/574380765
https://github.com/clearmatics/autonity/runs/574671480

TestTendermintStartStopFPlusTwoNodes
https://github.com/clearmatics/autonity/runs/585426726
https://github.com/clearmatics/autonity/runs/572227361

TestContractUpgradeSeveralUpgradesOnStarTopology
https://github.com/clearmatics/autonity/runs/573461126
https://github.com/clearmatics/autonity/runs/574047422

TestTendermintStarOverParticipantSuccess
https://github.com/clearmatics/autonity/runs/573651085
https://github.com/clearmatics/autonity/runs/574047654

TestTendermintStarOverParticipantSuccessWithExternalUser
https://github.com/clearmatics/autonity/runs/585096427
```

# Acceptance Criteria

Time successful runs of each test, then run 100 iterations (`-count 100`) of each test with a timeout of 2.5*<successful_run_time>*100. We should not see any failures. 

Provide the commands to run the tests in the PR so that reviewers can easily check for themselves.

 We set the timeout 2.5 times higher than the time for a successful run since that seems like a reasonable amount of leeway to allow for test time fluctuations.

**Comment by JekaMas** [comment]
2500s ?

**Comment by piersy** [comment]
2500s is calculated by allowing 25s per test run and having a count of 100. My understanding is that the timeout flag provides a global timeout, not a per run timeout.
