### ISSUE TITLE
Remove Bytecode and ABI fields from AutonityContractConfig 

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#513]
# Problem

The Autonity contract seems to be tightly coupled to the code of the Autonity project, you cannot simply specify your own Autonity contract in the genesis file and expect it to work. Providing the possibility for people to specify their own Autonity contract ABI and bytecode in the genesis file opens up the possibility for configuration errors.

I think it would be safer and simpler if we considered the Autonity project and the Autonity contract as a single unit that is versioned together.

**Comment by JekaMas** [comment]
Shall we provide this to a client? For me, it's not something that necessary.

Maybe we shall focus on core functionality and according docs? @yazzaoui

**Comment by yazzaoui** [comment]
I understand the concern but providing the flexibility to change the Autonity Contract is a very important feature of the client and we tried our best to make it as simple as possible to develop around it. That's probably what makes Autonity special. Also, in the near future, we want to provide the option to choose between 3 contracts: classical BFT, PoS and dPoS. 

But before that, we have to make progress on the most technically involved contract, dPoS.

**Comment by JekaMas** [comment]
I understand you. My question is about priorities. Maybe it's not a very good practice to add new issue into a sprint during the sprint. Such new issues could not match the current priorities.

**Comment by piersy** [comment]
@yazzaoui I guess I'm lacking the context about why it is so important to provide flexibility to change the contract, do you know if we have any documentation that explains the reasoning and use cases for this?

**Comment by yazzaoui** [comment]
@piersy It's not documented anywhere but flexibility for the economic mechanism is a nonfunctionnal requirement for Autonity as it is being definitely tied up to the final use case of the deployed network. That is to say, some consortiums might want to have an advanced model with stake delegation and slashing, some others might want something different. We're providing a general framework to support the maximum of use cases. 
Please see also the [Autonity Contract upgrade feature](https://github.com/clearmatics/autonity/issues/187) which could even allow a change of the Autonity contract and the economic model during the lifetime of a deployed network.

**Comment by yazzaoui** [comment]
24/06/2020 meeting notes:

- We should supply an interface for the Autonity Contract.
- The Autonity contract ABI in genesis.json field should be verified compliant against this interface.
- We keep the ABI and bytecode field in the genesis.json but we hide those fields in the doc until we figure out a safe way to publicly support that.
