### ISSUE TITLE
Make deployer address safe

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#527]
# Problem

The deployer address is a mechanism that we use to restrict certain function calls in the Autonity contract to be called only by the autonity client. The Autonity contract only accepts calls to the restricted functions if they come from the deployer address. Internally the client executes these functions by calling the EVM directly, bypassing any code that processes transactions and verifies transaction signatures, when it makes these calls it uses the deployer address as the sender address.

We want to ensure that no users know the private key for the deployer address, otherwise they would be able to send transactions that could execute the restricted system functions of the autonity contract.

At present users of a network have no way to know that the creator of the genesis does not hold the key to the deployer address, they would need to trust that the creator is not badly behaved.

# Implementation

I can see 2 ways to solve this issue.

 * Update the clients to drop any transactions coming from the deployer address, in this way even if the key was discovered, the key holder would not be able to manipulate the system functions. We can also hardcode the address at this point so we could go for the zero address.

* Generate the address at runtime based on the content of the genesis file (including the users), this ensures that no one party has control over the deployer address, and would be safe as long as no-one discovers the key.

# Acceptance Criteria

Participants do not have to trust that the creator of the genesis file does not hold the key to the genesis address.

# Notes

I think I prefer the first approach outlined above (drop transactions from deployer address), it seems conceptually simpler and doesn't run the risk that anyone can discover the key.

**Comment by aneequesafdar** [comment]
I am not sure we can simply drop the transaction from the deployer address since it is meant to be controlled by the operator and the operator is responsible for adding and removing participants from the Autonity contract, thus deployer's address is required to make such transactions.

Unless we somehow provide another way for the operator to change the participants, which I am not sure is a good idea since it would not be recorded on the blockchain.

**Comment by piersy** [comment]
@aneequesafdar I'm not following your explanation.

It seems like you are saying that the operator is able to change the deployer address.
> I am not sure we can simply drop the transaction from the deployer address since it is meant to be controlled by the operator

And also saying that the operator needs to use the deployer address to add or remove users.
> the operator is responsible for adding and removing participants from the Autonity contract, thus deployer's address is required to make such transactions

Looking at the current implementation of the [autonity contract](https://github.com/clearmatics/autonity/blob/17d0e50295eee2aee2c5609b185722f0e259b002/contracts/autonity/contract/contracts/Autonity.sol) I can see we have `onlyOperator` and `onlyDeployer` modifiers defined. If you look at the functions they are applied to you can see that the operator is free to add or remove users without relying on the deployer. We can also see that the deployer cannot be modified, it is only set when the contract is deployed.

**Comment by aneequesafdar** [comment]
Yeah seem like you are correct, I thought the deployer and operators were the same (I wasn't involved with developing the Autonity).

**Comment by yazzaoui** [comment]
What if we simply chose and hardcode `0x0000000000000000000000000000000000000`  for the deployer address?
To me, this leaves no doubt that no one owns the private key associated with this address ?

**Comment by piersy** [comment]
@yazzaoui simply hardcoding any address runs the risk that someone might have the key, admittedly it is a very small chance.

Actually I found [this](https://stackoverflow.com/questions/50580769/what-is-0x0-address-in-solidity-ethereum) discussion of the 0x0 address in ethereum. It seems that it is commonly referred to as the black hole, its where people send eth to "burn" it.

So given that the entire ethereum community believes the key to 0x0 will never be found I think it is a safe choice for the deployer address.

**Comment by yazzaoui** [comment]
Yeah I'm in favor of using 0x0, we'll have then to: 

- remove the  genesis file `deployer` config option
- adjust the Autonity contract deployment logic, as this address is transferred to the contract constructor
- modify the Autonity contract itself accordingly
