### ISSUE TITLE
Issues hit while following helloworld doc

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/autonity#657]
# Problem

While going through the helloworld instructions: https://docs.autonity.io/hello-autonity/compose.html
I hit a few issues:

1. the commands reference the command `autonity attach http://0.0.0.0:8541`, but there are no instructions to install autonity on the host (it's only available inside docker).

2. I use the following commands to check the current block height of each of the 5 nodes:
```console
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                 CREATED             STATUS              PORTS                                                                                                          NAMES
bae2d65c84b9        autonity:helloworld   "./autonity-start.sh"   12 minutes ago      Up 12 minutes       8546/tcp, 0.0.0.0:8543->8545/tcp, 0.0.0.0:8643->8645/tcp, 0.0.0.0:30333->30303/tcp, 0.0.0.0:30333->30303/udp   autonity-node-3
043634a197ff        autonity:helloworld   "./autonity-start.sh"   12 minutes ago      Up 12 minutes       8546/tcp, 0.0.0.0:8542->8545/tcp, 0.0.0.0:8642->8645/tcp, 0.0.0.0:30323->30303/tcp, 0.0.0.0:30323->30303/udp   autonity-node-2
b5d2d057d23a        autonity:helloworld   "./autonity-start.sh"   12 minutes ago      Up 12 minutes       8546/tcp, 0.0.0.0:8541->8545/tcp, 0.0.0.0:8641->8645/tcp, 0.0.0.0:30313->30303/tcp, 0.0.0.0:30313->30303/udp   autonity-node-1
413cc467fe03        autonity:helloworld   "./autonity-start.sh"   12 minutes ago      Up 12 minutes       0.0.0.0:8545->8545/tcp, 0.0.0.0:8645->8645/tcp, 8546/tcp, 0.0.0.0:30353->30303/tcp, 0.0.0.0:30353->30303/udp   autonity-node-5
ab5e773b4264        autonity:helloworld   "./autonity-start.sh"   12 minutes ago      Up 12 minutes       8546/tcp, 0.0.0.0:8544->8545/tcp, 0.0.0.0:8644->8645/tcp, 0.0.0.0:30343->30303/tcp, 0.0.0.0:30343->30303/udp   autonity-node-4
$ curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' 0.0.0.0:8541
{"jsonrpc":"2.0","id":1,"result":"0x2e3"}
$ curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' 0.0.0.0:8542
{"jsonrpc":"2.0","id":1,"result":"0x0"}
$ curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' 0.0.0.0:8543
{"jsonrpc":"2.0","id":1,"result":"0x0"}
$ curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' 0.0.0.0:8544
{"jsonrpc":"2.0","id":1,"result":"0x0"}
$ curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' 0.0.0.0:8545
{"jsonrpc":"2.0","id":1,"result":"0x0"}
```
It appears that only node-1 is advancing.  Not sure if I'm doing something wrong here.

(On a related note, it seems that the network is configured to have only node-1 as a validator - not sure if this was the intention, but it may be more interesting to include multiple nodes in consensus)

**Comment by piersy** [comment]
@dtebbs @AntoineRondelet I've updated the doc for helloworld in #655 to include fully dockerised commands for interacting with the docker compose nodes.

**Comment by dtebbs** [comment]
@piersy Thanks for the update.  I had a quick look at the new doc - great to have the docker command to get the console.

> Point 2 is worrying though!
Not sure if this will be still be an issue with the new docker image, but let me know if you need logs etc. from my side.

**Comment by piersy** [comment]
@dtebbs I discussed Point 2 with @yazzaoui and it actually seems like it is a fairly straightforward problem to solve, see the ticket for it here - #663

**Comment by piersy** [comment]
Closing this because the documentation has been updated and the second point has its own issue here - #663
