### ISSUE TITLE
Use json list of validators in Genesis file

### ISSUE THREAD

**Issue by JekaMas** [clearmatics/autonity#67]
It's an additional option. So user should be able to provide validators in one of two possible formats:
* as encoded extraData field
* as a list of node IDs

**Comment by yazzaoui** [comment]
I agree, good feature. But what happens if the user supplies both? Panic?

**Comment by JekaMas** [comment]
You could see it in the code: validators list have higher priority. Will add this into the doc.

**Comment by JekaMas** [comment]
closed by https://github.com/clearmatics/autonity/pull/68
