### ISSUE TITLE
Header marshalling is broken

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#675]
# Problem

There exist 2 methods for marshaling headers in autonity.

https://github.com/clearmatics/autonity/blob/e69cb4cbd472c5d0f88b817180f8f5e0fded375a/internal/ethapi/api.go#L1097

https://github.com/clearmatics/autonity/blob/e69cb4cbd472c5d0f88b817180f8f5e0fded375a/core/types/gen_header_json.go#L18

And a single method to unmarshal in `gen_header_json.go`. Using the marshaling method defined in `api.go` with the unmarshaling defined in `gen_header_json.go` doesn't work, because they are marshaling into different JSON structures.

Additionally both the marshaling methods are also broken:
* `RPCMarshalHeader` - because it doesn't correctly encode the additional fields that we have added to the header.
* `MarshalJSON` - because it is marshaling the fields added by Autonity to the extra data field, and this doesn't make sense because we have added them to the header. The extra data field exists to allow extra data to be passed around without having to add the fields to the header.

# Acceptance Criteria

* There should be just one marshal method for `types.Header`.
* We should only encode data  in extra data that is not a field on `types.Header`

**Comment by donmiguelenriquez** [comment]
Would not be more better to go back to the extraData field instead of adding the fields into the Header ?
When the breaking change was introduced in v0.4.0, I noticed that very little attention was paid to the issue that the Header change goes a bit far from the spec, besides then the fact that it is introducing new issues that could have been avoided and keep the compatibility that existed before. Not to mention the work around on `originalHeader` and both new methods `func (h *Header) DecodeRLP(s *rlp.Stream) error` and `func (h *Header) EncodeRLP(w io.Writer) error` that IMHO should not be there at all if the extraData compatibility was not dropped in favor of adding the fields directly into the Header.

**Comment by piersy** [comment]
Hi @donmiguelenriquez, thanks for your input, sorry about the delay in getting back to you.

I will try to address your questions.

> Would not be better to go back to the extraData field instead of adding the fields into the Header?

This is a fork of go-ethereum, so we have decided to change the header format to suit our needs.

That said we want to maintain, compatibility as much as we can with existing ethereum tooling, which means that when encoding to and decoding from rlp, we will use the extra header field, since rlp is sensitive to the number of fields in an object and trying to decode/encode an object with more fields than expected will fail. JSON however does not suffer these problems so we can add fields to the json representation of header without breaking the encoding/decoding. It's clear that for clients of Autonity it's nicer for them to not have to handle a further layer of decoding on top of the normal json decoding.

> When the breaking change was introduced in v0.4.0

I'm not sure what change you are referring to here if you could link to a commit I could comment further, I don't think that there should have been any intentional breaking change to the marshaling in 0.4.0, but there is of course this bug, which was unintentional.

> and keep the compatibility that existed before

What compatibility?

As I explained above, if executed correctly, this change should not, as far as I can see, have affected either RLP or JSON compatibility. If that is not the case please let me know!

> Not to mention the work around on originalHeader and both new methods func (h *Header) DecodeRLP(s *rlp.Stream) error and func (h *Header) EncodeRLP(w io.Writer) error that IMHO should not be there at all if the extraData compatibility was not dropped in favor of adding the fields directly into the Header.

I'm not really understanding what you are suggesting here. If we are going to encode/decode information in extraData, we need a mechanism to do it and that is what the EncodeRLP/DecodeRLP methods do. Or are you suggesting that we do not even add fields into the header and instead decode/encode the extra data at some other point in the code?
