### ISSUE TITLE
Add openNetwork parameter into Glienicke and Genesis

### ISSUE THREAD

**Issue by JekaMas** [clearmatics/autonity#69]
The context of the issue is here https://github.com/clearmatics/autonity/pull/61#discussion_r273853550

At the moment we have `opennetwork` value in a quite a few places:
 * a flag [opennetwork](https://github.com/clearmatics/autonity/blob/master/cmd/utils/flags.go#L525)
 * P2P layer, a field in [p2p.Config](https://github.com/clearmatics/autonity/blob/master/p2p/server.go#L95)
 * Core layer, a field in [BlockChain](https://github.com/clearmatics/autonity/blob/master/core/blockchain.go#L194) - _it is used, however, it is never initialized, so it's always `false`_
 * Eth layer, a field in [eth.Config](https://github.com/clearmatics/autonity/blob/master/eth/config.go#L146)
 * Eth layer, a field in [ProtocolManager](https://github.com/clearmatics/autonity/blob/master/eth/handler.go#L114)

And the initialization happens in 2 places:
* SetEthConfig
* SetP2PConfig

The main idea is to extract the parameter into Genesis and make it updatable through `Glienicke` contract.

@yazzaoui @cmjc @ya @aiman

**Comment by yazzaoui** [comment]
On standby, until we get sign-off from product.

**Comment by JekaMas** [comment]
@yazzaoui I think we still need this issue.

**Comment by cmjc** [comment]
Hi @yazzaoui , @JekaMas - Sorry for delay and @flofrie the product owner is now aware of this.

Looking at the code references,I agree it makes sense to rationalise multiple instances of the parameter and to simplify the config into the genesis. I cannot think of a reason not to do this but will continue to think on it.

@flofrie will give official sign-off.

I'm sorry for not having seen and acted on this 12 days ago.

**Comment by flofrie** [comment]
Would also be interested in @cmjc 's perspective, but my thoughts:

**Comment by flofrie** [comment]
As I understand from a conversation with @cmjc just now, @yazzaoui will formulate more precisely what the actual question/issue is. My current view: yes, makes sense to have a single place at Genesis to define whether it's an open network or not; I believe there is NO scenario in which we intend to change an open network into a closed/permissioned one *during run time*, or vice versa, so having a simple single parameter that's set at Genesis seems to make sense.

**Comment by aneequesafdar** [comment]
Another reason as to why we would like to have this option is for testing the consensus algorithm. Defining permissioned nodes every time we bring up a network is very cumbersome especially when we bring up networks multiple times during the day. From what @cmjc has already said [here](https://github.com/clearmatics/autonity/pull/61#discussion_r273853550) I don't see why we shouldn't have this option.

**Comment by yazzaoui** [comment]
Closing as no requirements for it.
