### ISSUE TITLE
Decide on compatibility with the Light Ethereum Subprotocol

### ISSUE THREAD

**Issue by flofrie** [clearmatics/autonity#77]
From an Architecture point of view, we do not currently assume that we will provide a light client; however, our current policy has been for Autonity to remain compatible with the LES. We should discuss whether this policy makes sense and is not too burdensome, or whether there are valid considerations for not pursuing LES compatibility for now.

**Comment by JekaMas** [comment]
I have a few thoughts about it. First of all, we need to add epoch/checkpoint logic into IBFT or a new implementation of Tendermint as it was done in https://github.com/ethereum/go-ethereum/pull/17466 to make LES capable with our consensus.
And the second thing, it may be easier to support ULC option of LES than all LES. Also ULC is 6-10 times faster than LES and it's all about an idea of trusted nodes: https://hackmd.io/s/HJy7jjZpm

**Comment by flofrie** [comment]
As I understand it, @rmsams and @shapeshed don't view EEA compliance as top of the priority list, so there isn't an overriding imperative from that side on maintaining LES compatibility. Who can give us a good view on what other reasons there may be for us to maintain LES compatibility (if we assume also that we won't have an Autonity Light Client on the roadmap for some time, if at all)?

**Comment by shapeshed** [comment]
EEA compliance is a priority :smile: I can talk through the relevant part of the spec, although there isn't currently an implementable specification for EEA clients

**Comment by yazzaoui** [comment]
@JekaMas 
In our current implementation, IBFT-Soma is LES-compatible. The list of validators for the next block are saved in the current block extradata field, so it's effectively a chain of trust with the 2F+1 commits. I see no reasons why it shouldn't be the same with Tendermint.

The problem is that this approach breaks the compatibility of Autonity with other clients implementing vanilla IBFT..

**Comment by aneequesafdar** [comment]
@flofrie I believe it can be done but our first priority is implementing full node Tednermint. Depending on the roadmap we can allocate time for it.

**Comment by yazzaoui** [comment]
@flofrie any update with this regard? What's the view on EEA compliance?

**Comment by flofrie** [comment]
Good question. I honestly don't know who would make a final decision on this, and how, but how about I take it into the System X Structuring meeting, and see how that discussion pans out ...
