### ISSUE TITLE
Consider moving hello world to its own repository

### ISSUE THREAD

**Issue by shapeshed** [clearmatics/autonity#78]
The hello world folder uses a docker image hosted on Docker Hub so there is no need to download the entire Autonity codebase.

In order to promote people being able to try out the hello world as easily as possible it is suggested that this folder is moved to its own repository. This would allow the end user to get started more quickly and not have to wait to download all of the Autonity codebase which is not required. 

Please +1 or -1 and not any objections.

**Comment by JekaMas** [comment]
It's closely related to the need to have Autonity versioning, I think. We should define the way we have new versions of Autonity, remove old Ethereum tags and add new ones. @eastata

**Comment by eastata** [comment]
**+1** 
I had the same thoughts today. 

> The hello world folder uses a docker image hosted on Docker Hub

It is not true, but it's good idea

**Comment by shapeshed** [comment]
Closing this since it covered by the documentation effort.
