### ISSUE TITLE
Sort whitelist before contract deploy

### ISSUE THREAD

**Issue by JekaMas** [clearmatics/autonity#87]
`backend.getValidators()` is called many times until Genesis is committed to the blockchain. And `genesis.Commit()` is called 2-3 times also.
So `DeployGlienickeContract` should be deployed each time with exactly the same code and data. In the other case, it can lead to inconsistent StateDb.

P.S. I've tried to go deeper to understand how this can happen that `genesis.Commit()` is called many times. However, after an hour, I realised that it can take the whole day or more to find the cause and anyway we're going to rewrite the consensus.

By far we'll see multiple `Deployed Glienicke Contract` in the logs.

**Comment by aneequesafdar** [comment]
@JekaMas can you please give more context as to how sorting the whitelist will solve the issue? I don't fully understand the issue either?

**Comment by JekaMas** [comment]
As far as `types.Nodes` work in a concurrent way, the list of nodes won't be in the same order from call to call. This leads to the issue, that the contract will be deployed with the different state a few times in genesis block, and it'll lead to inconsistent StateDB.
