### ISSUE TITLE
Changing config consensus to tendermint doesn't affect anything

### ISSUE THREAD

**Issue by JekaMas** [clearmatics/autonity#95]
It looks like that the default config is always used and user-defined config is ignored.

So `HelloWorld` application doesn't work with Tendermint consensus

**Comment by aneequesafdar** [comment]
Can you please explain which config was not being overwritten and why was it working for IBFT and not Tendermint?

**Comment by JekaMas** [comment]
Just to keep context:
The issue is about the hard-coded Istanbul config. It was hardcoded as a default and only config https://github.com/clearmatics/autonity/pull/98/files#diff-21609b3ea13b7a6695113bee0fd055acL64 that used than in ` eth.Default`

**Comment by JekaMas** [comment]
via #98
